# Matrices & Vectors
## Review: Linear Algebra


---

## Matricies: Rectangular array of numbers
$
    \begin{bmatrix}
    1344 & 221 \\
    1371 & 821 \\
    949  & 1437 \\
    147  & 1448
    \end{bmatrix} \rightarrow \mathbb{R}^{4\times2}
$

$
    \begin{bmatrix}
    1 & 2 & 3 \\
    4 & 5 & 6 \\
    \end{bmatrix} \rightarrow \mathbb{R}^{2\times3}
$

### Dimension of matrix: number of rows $\times$ number of columns

$
    A = \begin{bmatrix}
    1344 & 221 \\
    1371 & 821 \\
    949  & 1437 \\
    147  & 1448
    \end{bmatrix} \rightarrow \mathbb{R}^{4\times2}
$

### $A_{ij}:$ $i,j$ entry in the $i^{th}$ row $j^{th}$ comlumns

$A_{11} = 1344$ 

$A_{12} = 221$  

$A_{32} = 1437$ 

$A_{41} = 147$ 

$A_{43} = Undefined$

### **Note:** in computers, $i,j$ start from $0$, not $1$ 
$A[1,1] = 821$

---

## Vector: An $n\times1$ matrix

$
    y = \begin{bmatrix}
    460 \\
    232 \\
    315 \\
    178
\end{bmatrix} \rightarrow \mathbb{R}^4 $

### $y_{i}:$ $i^{th}$ element

$y_{1} = 460$ 

$y_{2} = 232$  

$y_{3} = 315$ 


$A_{43} = Undefined$

### **Note:** in computers, $i$ starts from $0$, not $1$ 
$y[1] = 232$

---

## Matrix Addition

$
\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix}_{(3\times2)}
+
\begin{bmatrix}
4 & 0.5 \\
2 & 5 \\
0 & 1
\end{bmatrix}_{(3\times2)}
=
\begin{bmatrix}
5 & 0.5 \\
4 & 10 \\
3 & 2
\end{bmatrix}_{(3\times2)}
$


$
\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix}_{(3\times2)}
+
\begin{bmatrix}
4 & 0.5 \\
2 & 5 \\
\end{bmatrix}_{(2\times2)}
= ERROR
$

## Matrix Scalar Multiplication

$
3 \times
\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix}
=
\begin{bmatrix}
3 & 0 \\
6 & 15 \\
9 & 3 \\
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 \\
2 & 5 \\
3 & 1 \\
\end{bmatrix} \times 3
$

$
\begin{bmatrix}
4 & 0 \\
6 & 5 \\
\end{bmatrix} /4
= 
\begin{bmatrix}
1 & 0 \\
\frac{3}{2} & \frac{5}{4} \\
\end{bmatrix}
$

## Combination of Operands

$
3 \times 
\begin{bmatrix}
1 \\ 4 \\ 2
\end{bmatrix}
+
\begin{bmatrix}
0 \\ 0 \\ 5
\end{bmatrix}
-
\begin{bmatrix}
3 \\ 0 \\ 2
\end{bmatrix}
/3
$

$
\quad=
\begin{bmatrix}
3 \\ 12 \\ 6
\end{bmatrix}
+
\begin{bmatrix}
0 \\ 0 \\ 5
\end{bmatrix}
-
\begin{bmatrix}
1 \\ 0 \\ \frac{2}{3}
\end{bmatrix}
$

$
\begin{bmatrix}
2 \\ 12 \\11-\frac{2}{3}
\end{bmatrix}
=
\begin{bmatrix}
2 \\ 12 \\ \frac{33-2}{3}
\end{bmatrix}
=
\begin{bmatrix}
2 \\ 12 \\ \frac{31}{3}
\end{bmatrix}
=
\begin{bmatrix}
2 \\ 12 \\ 10\frac{1}{3}
\end{bmatrix}
$

## Matrix-Vector Multiplication

$
\begin{bmatrix}
1 & 3 \\
4 & 0 \\
2 & 1
\end{bmatrix}_{3\times2}
\begin{bmatrix}
1 \\ 5
\end{bmatrix}_{2\times1}
=
\begin{bmatrix}
(1\times1) + (3\times5) \\
(4\times1) + (0\times5) \\
(2\times1) + (1\times5) \\
\end{bmatrix}
=
\begin{bmatrix}
(1) + (15) \\
(4) + (0) \\
(2) + (5) \\
\end{bmatrix}
=
\begin{bmatrix}
16 \\
4 \\
7
\end{bmatrix}_{3\times1}
$


### Method: if $A$ is a matrix, $x$ is a vector, then to get $y = A \times x$: multiply $A$'s $i^{th}$ row with the elements of $x$, and add them up


### Example:
$
\begin{bmatrix}
1 & 2 & 1 & 5 \\
0 & 3 & 0 & 4 \\
-1 & -2 & 0 & 0 \\
\end{bmatrix}_{3\times4}
\begin{bmatrix}
1 \\ 3 \\ 2 \\ 1
\end{bmatrix}_{4\times1}
=
\begin{bmatrix}
(1\times1) + (2\times3)  + (1\times2) + (5\times1)\\
(0\times1) + (3\times3)  + (0\times2) + (4\times1)\\
(-1\times1) + (-2\times3)  + (0\times2) + (0\times1)\\
\end{bmatrix}
=
\begin{bmatrix}
(1) + (6) + (2) + (5) \\
(0) + (9) + (0) + (4) \\
(-1) + (-6) + (0) + (0) \\
\end{bmatrix}
=
\begin{bmatrix}
14 \\
13 \\
-7
\end{bmatrix}_{3\times1}
$

## Matrix-Matrix Multiplication

$
\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1\\
\end{bmatrix}_{2\times3}
\begin{bmatrix}
1 & 3 \\
0 & 1 \\ 
5 & 2
\end{bmatrix}_{3\times2}
$

---

$
\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1\\
\end{bmatrix}_{2\times3}
\begin{bmatrix}
1 \\
0 \\ 
5
\end{bmatrix}_{3\times1}
=
\begin{bmatrix}
11\\
9
\end{bmatrix}_{2\times1}
$

$
\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1\\
\end{bmatrix}_{2\times3}
\begin{bmatrix}
3 \\
1 \\ 
2
\end{bmatrix}_{3\times1}
=
\begin{bmatrix}
10\\
14
\end{bmatrix}_{2\times1}
$

---

$
\begin{bmatrix}
1 & 3 & 2 \\
4 & 0 & 1\\
\end{bmatrix}_{2\times3}
\begin{bmatrix}
1 & 3 \\
0 & 1 \\ 
5 & 2
\end{bmatrix}_{3\times2}
=
\begin{bmatrix}
11 & 10\\
9  & 14
\end{bmatrix}_{2\times2}
$

### Example:

$
\begin{bmatrix}
1 & 3 \\
2 & 5 \\
\end{bmatrix}_{2\times2}
\begin{bmatrix}
0 & 1 \\
3 & 2 \\
\end{bmatrix}_{2\times2}
=
\begin{bmatrix}
\big((1\times0)+(3\times3)\big) & \big((1\times1)+(3\times2)\big) \\
\big((2\times0)+(5\times3)\big) & \big((2\times1)+(5\times2)\big) \\
\end{bmatrix}_{2\times2}
=
\begin{bmatrix}
\big(0+9\big) & \big(1+6\big) \\
\big(0+15\big) & \big(2+10\big) \\
\end{bmatrix}_{2\times2}
=
\begin{bmatrix}
9 & 7 \\
15 & 12 \\
\end{bmatrix}_{2\times2}
$

## Matrix Multiplication Properties
### if $A$ and $B$ are matrices:

#### In general: $A \times B \neq B \times A$ (not commutative)

### Example:
$
\begin{bmatrix}
1 & 1 \\
0 & 0 \\
\end{bmatrix}_{2\times2}
\begin{bmatrix}
0 & 0 \\
2 & 0 \\
\end{bmatrix}_{2\times2}
=
\begin{bmatrix}
2 & 0 \\
0 & 0 \\
\end{bmatrix}_{2\times2}
$

$\neq$

$
\begin{bmatrix}
0 & 0 \\
2 & 0 \\
\end{bmatrix}_{2\times2}
\begin{bmatrix}
1 & 1 \\
0 & 0 \\
\end{bmatrix}_{2\times2}
=
\begin{bmatrix}
0 & 0 \\
2 & 2 \\
\end{bmatrix}_{2\times2}
$

#### $ A \times B \times C = A \times (B \times C) = (A \times B) \times C $

### Identity Matrix 

$
I_{(2\times2)} = 
\begin{bmatrix}
1 & 0 \\
0 & 
\end{bmatrix}
$

$
I_{(3\times3)} = 
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{bmatrix}
$

$
I_{(4\times4)} = 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1 \\
\end{bmatrix}
$

#### For any matrix $A$: $A \times I = I \times A = A$

### Inverse of a Matrix
#### $A_{(n \times n)} \times A^{-1} = A^{-1} \times A = I$

if $A = \begin{bmatrix}
        a_{11} & a_{12} \\
        a_{21} & a_{22}
        \end{bmatrix}
   $
then 
$
A^{-1} = \frac{1}{a_{11}a_{22}-a_{12}a_{21}} \times \begin{bmatrix}
                                                        a_{22} & -a_{12} \\
                                                        -a_{21} & a_{11}
                                                        \end{bmatrix}
$
### Example:
$
\begin{bmatrix}
3 & 4 \\
2 & 16\\
\end{bmatrix}
\begin{bmatrix}
0.4 & -0.1 \\
-0.05 & 0.075 \\
\end{bmatrix}
=
\begin{bmatrix}
1 & 0 \\
0 & 1 \\
\end{bmatrix}
$

### Matrix Transpose
if 
$
A = \begin{bmatrix}
1 & 2 & 0 \\
3 & 5 & 9 \\
\end{bmatrix}
$

$
A^T = \begin{bmatrix}
1 & 3 \\
2 & 5 \\
0 & 9 \\
\end{bmatrix}
$

# Introducing NumPy

In [23]:
import numpy as np # np is an alias for numpy module

In [15]:
lst = [1,2,3,4]

In [20]:
arr = np.array(lst)

In [22]:
print(type(arr))

<class 'numpy.ndarray'>


#### NumPy is faster that lists
1. NumPy arrays are saved in adjacent location in memory, Unlike Lists, which are linked lists.
2. Numpy operations are optimized for faster performance
3. Some of the NumPy operation are in C/C++ $\rightarrow$ faster

In [45]:
arr = np.array(43)
print('arr:', arr) # 0-D array
print('type(arr):', type(arr))
print('arr.shape:', arr.shape)
print('arr[0]:', arr[0])

arr: 43
type(arr): <class 'numpy.ndarray'>
arr.shape: ()


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [44]:
arr = np.array([1,2,3,4])
print(arr) # 1-D array
print('type(arr):', type(arr))
print('arr.shape:', arr.shape)
print('arr[0]:', arr[0])
print('arr[3]:', arr[3])
print('arr[4]:', arr[4])

[1 2 3 4]
type(arr): <class 'numpy.ndarray'>
arr.shape: (4,)
arr[0]: 1
arr[3]: 4


IndexError: index 4 is out of bounds for axis 0 with size 4

In [47]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr) # 2-D array
print('type(arr):', type(arr))
print('arr.shape:', arr.shape)
print('arr[0]:', arr[0])
print('arr[1,2]:', arr[1,2])
print('arr[3]:', arr[3])

[[1 2 3 4]
 [5 6 7 8]]
type(arr): <class 'numpy.ndarray'>
arr.shape: (2, 4)
arr[0]: [1 2 3 4]
arr[1,2]: 7


IndexError: index 3 is out of bounds for axis 0 with size 2

In [53]:
print(arr.ndim) # deminsions of the NumPy array
print(len(arr.shape))

5
5


In [55]:
arr = np.array([1,2,3,4], ndmin=5)
print(arr.shape)
print(arr)

(1, 1, 1, 1, 4)
[[[[[1 2 3 4]]]]]


In [61]:
arr = np.array([1,2,3,4,5,6,7])

In [62]:
print(arr[2:4]) #slicing

[3 4]


In [63]:
print(arr[2:]) #slicing till the end

[3 4 5 6 7]


In [68]:
print(arr[::2]) # slicing with step 2

[1 3 5 7]


In [67]:
print(arr[-3:]) # slicing starting from the third element from the right till the end

[5 6 7]


In [69]:
print (arr[-3::-1]) #slicing startign from the third element from the right till the beginning with step 1

[5 4 3 2 1]


In [82]:
arr_1 = np.array([1,2,3])

print("Assigning array to variable")
arr_2 = arr_1 
arr_2[2] = 333
print('arr_1:', arr_1)
print('arr_2:', arr_2)

print("\nAssigning array-copy to variable")
arr_2 = arr_1.copy()
arr_2[1] = 222
print('arr_1:', arr_1)
print('arr_2:', arr_2)


Assigning array to variable
arr_1: [  1   2 333]
arr_2: [  1   2 333]

Assigning array-copy to variable
arr_1: [  1   2 333]
arr_2: [  1 222 333]


In [85]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [87]:
print(arr.reshape((4,3))) # reshape from (12) to (4,3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [93]:
print(arr.reshape((2,3,2))) # reshape from (12) to (2,3,2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [101]:
print(arr.reshape((2,-1))) # reshape from (12) to (2,whatever)

[[99  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [115]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr_2 = arr.reshape(6,2) # reshape returns a view for the original array
print(arr_2)
arr_2[0,1] = 99
print()
print(arr_2)
print()
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[[ 1 99]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[ 1 99  3  4  5  6  7  8  9 10 11 12]


In [120]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print()
print(arr.reshape(-1))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]


In [123]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [126]:
for i in arr:
    print('i:', i)
    for j in i:
        print('\tj:', j)
        for k in j:
            print('\t\tk:', k)

i: [[1 2]
 [3 4]]
	j: [1 2]
		k: 1
		k: 2
	j: [3 4]
		k: 3
		k: 4
i: [[5 6]
 [7 8]]
	j: [5 6]
		k: 5
		k: 6
	j: [7 8]
		k: 7
		k: 8


In [130]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [132]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [134]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [139]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))
print(arr)
print()
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]


In [141]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [146]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

print( np.where(arr == 4))

(array([3, 5, 6]),)


In [149]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [153]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [166]:
arr = np.arange(10)

print(arr)

print([arr>7])

print(arr[arr>7])

[0 1 2 3 4 5 6 7 8 9]
[array([False, False, False, False, False, False, False, False,  True,
        True])]
[8 9]


In [253]:
print(np.random.randint(100))
print()
print(np.random.rand())
print()
print(np.random.randint(100, size=(3,2)))
print()
print(np.random.rand(10))
print()
print(np.random.rand(10,2))

69

0.6689963626994175

[[20 79]
 [99 45]
 [72 51]]

[0.79128347 0.71306665 0.61800103 0.70676265 0.15253535 0.10026946
 0.34250941 0.97822989 0.88144669 0.099073  ]

[[0.6392073  0.60639403]
 [0.53096467 0.13553979]
 [0.63812617 0.33839174]
 [0.11523351 0.10270136]
 [0.16409917 0.0412766 ]
 [0.22859886 0.27532929]
 [0.46738024 0.89338548]
 [0.03739342 0.97102416]
 [0.34014675 0.84793477]
 [0.15926268 0.27951474]]


In [279]:
x = np.random.choice([3, 5, 7, 9])

print(x)

5


In [284]:
x = np.random.choice([3, 5, 7, 9], size=(3,5))

print(x)

[[5 9 3 7 5]
 [9 7 5 7 3]
 [9 3 3 5 3]]


In [299]:
lst_1 = [1,2,3,4]
lst_2 = [5,6,7,8]
print (lst_1+lst_2)
arr_1 = np.array(lst_1)
arr_2 = np.array(lst_2)

print(arr_1+arr_2)

print(np.add(lst_1,lst_2))

lst = [[1,2,3], [5,6,7]]
# print(sum(lst))
print(np.sum(lst))
print(np.sum(lst, axis=0))
print(np.sum(lst, axis=1))

print(np.cumsum(lst_1)) # 1,1+2,1+2+3,1+2+3+4

[1, 2, 3, 4, 5, 6, 7, 8]
[ 6  8 10 12]
[ 6  8 10 12]
24
[ 6  8 10]
[ 6 18]
[ 1  3  6 10]


In [305]:
print(np.prod([lst_1,lst_2]))
print(np.prod([lst_1,lst_2], axis=1))
print(np.cumprod(lst))

40320
[  24 1680]
[ 1  2  6 24]
